version: "3"
services:
  tgmusicbot:
    image: tgmusicbot:latest
    container_name: tgmusicbot
    # network_mode: "host"
    env_file: .env
    user: 1000:1000
    ports:
      - "4001:80"
    volumes:
      - type: bind
        source: /media/Magic/netbug/Music/ARTISTS
#        source: /media/Magic/netbug/Music/Download
        target: /media
      - type: bind
        source: /var/log/tgmusicbot
        target: /tmp/log
    restart: always
